#!/bin/sh

set -ue

# Pushes docker as part of `deploy` or from a trigger tag

version=${1:-master}

# handle trigger pattern like /^docker-[0-9]+\.[0-9]+\.[0-9]+$/
case ${version} in
  docker-* )
    version=$(build-bin/git/version_from_trigger_tag docker- ${version})
    ;;
esac

# openzipkin is named differently in docker.io (openzipkincontrib). Skip the latter for now.
export DOCKER_RELEASE_REPOS=ghcr.io
build-bin/docker/docker_push openzipkin/zipkin-gcp ${version}
