#!/bin/bash

set -v

# Export service account key from environmental variable to a file,
# so that it can be consumed by the Docker container
echo $GOOGLE_APPLICATION_CREDENTIALS_BASE64 | base64 -D > /tmp/service-account-key.json

# Download wait-for-it as it isn't yet available as an Ubuntu Xenial package
curl -sSL https://raw.githubusercontent.com/openzipkin-contrib/wait-for-it/master/wait-for-it.sh > wait-for-it.sh
chmod 755 wait-for-it.sh

docker run -d -p 9411:9411 \
  --name zipkin-gcp
  -e STORAGE_TYPE=stackdriver \
  -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account-key.json \
  -e STACKDRIVER_PROJECT_ID=zipkin-gcp-ci \
  $IMAGE_NAME

# In case something bad happens, kill the server!
trap 'docker kill zipkin-gcp' ERR INT

echo "Waiting for Zipkin server to start..."
./wait-for-it.sh localhost:9411 -t 60
exit_status=$?
if [ $exit_status -ne 0 ]; then
  exit $exit_status
fi

echo "Zipkin server started, waiting for OK health result..."
curl --silent localhost:9411/info | jq .

health_check_result=$(curl --silent localhost:9411/health | jq -r .status)

if [ "$health_check_result" != "UP" ]; then
  echo "Health check failed!"
  curl --silent localhost:9411/health | jq .
  exit 1
else
  echo "Health check status is up!"
fi

docker kill zipkin-gcp
