apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: zipkin
    spec:
      selector:
        app: zipkin-stackdriver
      ports:
        - protocol: TCP
          targetPort: 9411
          port: 9411
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: zipkin-stackdriver
      labels:
        app: zipkin-stackdriver
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: zipkin-stackdriver
        spec:
          containers:
            - name: zipkin-stackdriver
              image: gcr.io/stackdriver-trace-docker/zipkin-collector
              imagePullPolicy: Always
              env:
                - name: PROJECT_ID
                  value: my_project_id
              ports:
                - protocol: TCP
                  containerPort: 9411
